-- ============================================================
-- AlizQuiz — questions_extra.sql
-- Ajoute 18 questions supplémentaires par thème (is_extra = 1)
-- pour le Quiz Personnalisé, sans toucher aux quiz officiels.
-- ============================================================

ALTER TABLE quiz ADD COLUMN IF NOT EXISTS is_extra TINYINT(1) NOT NULL DEFAULT 0;

-- ============================================================
-- DÉBUTANT — Mots de passe (+18)
-- ============================================================
INSERT INTO quiz (niveau, theme, question, reponse1, reponse2, reponse3, reponse4, bonne_reponse, is_extra) VALUES
('debutant','Mots de passe','Quelle longueur minimale est généralement recommandée pour un mot de passe sécurisé ?','4 caractères','8 caractères','12 caractères','6 caractères',3,1),
('debutant','Mots de passe','Qu''est-ce qu''un gestionnaire de mots de passe ?','Un logiciel qui stocke et génère des mots de passe de façon sécurisée','Un antivirus amélioré','Un programme qui supprime les mots de passe oubliés','Un navigateur web spécialisé',1,1),
('debutant','Mots de passe','Lequel de ces mots de passe est le plus sécurisé ?','123456','motdepasse','P@ssw0rd!2024#','azerty',3,1),
('debutant','Mots de passe','Combien de temps faut-il idéalement pour renouveler ses mots de passe importants ?','Jamais, un bon mot de passe est permanent','Tous les jours','Régulièrement, surtout après une fuite de données','Uniquement quand on l''oublie',3,1),
('debutant','Mots de passe','Qu''est-ce que le "credential stuffing" ?','Un test de performances réseau','L''utilisation de couples identifiant/mot de passe volés pour tenter de se connecter à d''autres sites','Une technique de chiffrement','Un type de sauvegarde',2,1),
('debutant','Mots de passe','Que faire si vous soupçonnez qu''un de vos mots de passe a été compromis ?','Attendre quelques jours pour confirmer','Le changer immédiatement sur tous les sites concernés','En parler à un ami','Ignorer, c''est probablement faux',2,1),
('debutant','Mots de passe','Quelle est la différence entre un mot de passe et une phrase de passe ?','Il n''y a aucune différence','Une phrase de passe est plus courte','Une phrase de passe est une séquence de mots longue, plus facile à retenir et plus sûre','Un mot de passe est toujours plus sécurisé',3,1),
('debutant','Mots de passe','Quel type de caractère renforce le plus un mot de passe court ?','Des espaces','Des chiffres en fin de mot','Des caractères spéciaux mélangés (!, @, #...)','Des majuscules uniquement',3,1),
('debutant','Mots de passe','Pourquoi ne faut-il pas noter ses mots de passe sur un post-it collé sur son écran ?','C''est interdit par la loi','N''importe qui peut le lire et accéder à vos comptes','Cela abîme l''écran','Les post-its s''effacent trop vite',2,1),
('debutant','Mots de passe','Qu''est-ce qu''une attaque par dictionnaire sur un mot de passe ?','Une attaque utilisant des définitions de mots','Un test exhaustif de mots courants et de variantes pour deviner le mot de passe','Une méthode pour voler des livres numériques','Une technique de phishing',2,1),
('debutant','Mots de passe','Quel est le danger d''utiliser le même mot de passe partout ?','Aucun danger particulier','Si un seul site est compromis, tous vos comptes sont en danger','Cela ralentit la connexion','Les sites refusent les mots de passe identiques',2,1),
('debutant','Mots de passe','Quelle pratique est déconseillée pour choisir un mot de passe ?','Utiliser des caractères spéciaux','Utiliser le prénom de son animal de compagnie','Mélanger majuscules et minuscules','Utiliser des chiffres non consécutifs',2,1),
('debutant','Mots de passe','Que se passe-t-il lorsqu''un site stocke votre mot de passe "en clair" ?','Votre mot de passe est compressé','En cas de fuite, votre mot de passe est directement lisible par les attaquants','Votre mot de passe est plus rapide à vérifier','C''est la méthode la plus sécurisée',2,1),
('debutant','Mots de passe','Pourquoi certains sites bloquent-ils le compte après plusieurs tentatives de connexion échouées ?','Pour économiser de la bande passante','Pour se protéger contre les attaques par force brute','Pour forcer les utilisateurs à changer de mot de passe','C''est une obligation légale',2,1),
('debutant','Mots de passe','Qu''est-ce que l''authentification biométrique ?','Un mot de passe très long','Une identification basée sur des caractéristiques physiques (empreinte, visage...)','Un code envoyé par SMS','Un captcha amélioré',2,1),
('debutant','Mots de passe','Quel est le principal avantage d''un gestionnaire de mots de passe ?','Il supprime le besoin d''internet','Il permet de retenir un seul mot de passe maître pour gérer des dizaines de mots de passe uniques','Il remplace l''antivirus','Il est gratuit dans tous les cas',2,1),
('debutant','Mots de passe','Un site vous demande de créer un mot de passe de minimum 8 caractères. Lequel choisir ?','12345678','abcdefgh','K#9mP!rZ','password',3,1),
('debutant','Mots de passe','Qu''est-ce que le "hachage" d''un mot de passe ?','Le fait de le raccourcir','Une transformation irréversible du mot de passe en une empreinte numérique','Un chiffrement déchiffrable','Une compression du mot de passe',2,1),

-- ============================================================
-- DÉBUTANT — Virus (+18)
-- ============================================================
('debutant','Virus','Qu''est-ce qu''un cheval de Troie (Trojan) ?','Un virus qui se propage par Wi-Fi','Un logiciel malveillant qui se déguise en programme légitime','Un type d''antivirus','Un protocole réseau',2,1),
('debutant','Virus','Qu''est-ce qu''un ver informatique ?','Un virus qui infecte uniquement les fichiers audio','Un logiciel malveillant qui se propage seul de machine en machine sans action de l''utilisateur','Un programme d''optimisation disque','Un type de pare-feu',2,1),
('debutant','Virus','Quel est le principal vecteur d''infection par virus aujourd''hui ?','Les disquettes','Les fichiers malveillants reçus par email ou téléchargés sur internet','Les câbles réseau','L''écran de l''ordinateur',2,1),
('debutant','Virus','Que fait un logiciel espion (spyware) ?','Il améliore les performances du PC','Il collecte des informations sur l''utilisateur à son insu','Il bloque les publicités','Il accélère la connexion internet',2,1),
('debutant','Virus','Qu''est-ce qu''un adware ?','Un logiciel antivirus gratuit','Un logiciel qui affiche des publicités non désirées','Un type de pare-feu','Un outil de sauvegarde',2,1),
('debutant','Virus','Comment un virus peut-il se propager d''un ordinateur à un autre ?','Uniquement par câble USB','Via des fichiers infectés partagés, emails, ou réseaux','Par la chaleur du processeur','Par le son des haut-parleurs',2,1),
('debutant','Virus','Qu''est-ce qu''une "mise en quarantaine" dans un antivirus ?','La suppression immédiate d''un fichier','L''isolation d''un fichier suspect pour l''empêcher d''agir sans le supprimer définitivement','Un scan complet du disque','La désactivation du réseau',2,1),
('debutant','Virus','Pourquoi est-il dangereux d''exécuter un fichier .exe reçu par email d''un inconnu ?','Les fichiers .exe ne s''ouvrent pas par email','Un .exe peut contenir un programme malveillant qui s''installe sur votre machine','Les fichiers .exe sont trop lourds pour les emails','C''est interdit par les fournisseurs de messagerie',2,1),
('debutant','Virus','Qu''est-ce qu''un rootkit ?','Un antivirus très puissant','Un logiciel malveillant qui se cache profondément dans le système pour éviter d''être détecté','Un type de clé USB','Un outil de récupération de données',2,1),
('debutant','Virus','Quelle action est la plus efficace pour éviter les infections par virus ?','Éteindre son PC chaque soir','Combiner un antivirus à jour, des mises à jour régulières et une navigation prudente','Utiliser uniquement internet Explorer','Désactiver le Wi-Fi',2,1),
('debutant','Virus','Qu''est-ce qu''un botnet ?','Un réseau d''imprimantes sécurisées','Un réseau de machines infectées contrôlées à distance par un attaquant','Un type de réseau Wi-Fi','Un antivirus collaboratif',2,1),
('debutant','Virus','Que signifie "malware" ?','Logiciel mal conçu','Logiciel malveillant (malicious software) destiné à nuire','Mauvais matériel informatique','Logiciel de maintenance',2,1),
('debutant','Virus','Un ami vous envoie un lien en disant "regarde cette vidéo drôle". Que faire ?','Cliquer immédiatement','Vérifier l''URL et s''assurer que le lien est sûr avant de cliquer','Transférer le lien à tous vos contacts','Ignorer définitivement cet ami',2,1),
('debutant','Virus','Qu''est-ce que la détection heuristique dans un antivirus ?','Une détection basée uniquement sur les signatures connues','Une analyse du comportement des programmes pour détecter des menaces inconnues','Un scan planifié hebdomadaire','Une vérification de la connexion internet',2,1),
('debutant','Virus','Pourquoi les virus ciblent-ils souvent les fichiers système ?','Pour améliorer les performances','Pour persister sur la machine et se relancer automatiquement à chaque démarrage','Pour libérer de l''espace disque','Pour accélérer les mises à jour',2,1),
('debutant','Virus','Qu''est-ce qu''un virus polymorphe ?','Un virus qui attaque plusieurs systèmes à la fois','Un virus qui modifie son propre code pour échapper à la détection','Un virus spécialisé dans les smartphones','Un virus détectable uniquement la nuit',2,1),
('debutant','Virus','Quel type de fichier est statistiquement le plus souvent porteur de malware dans les emails ?','Fichiers .txt','Fichiers .pdf, .doc/.docx avec macros et .exe','Fichiers .jpg','Fichiers .mp3',2,1),
('debutant','Virus','Après avoir détecté un virus, quelle est la première action recommandée ?','Redémarrer immédiatement','Déconnecter la machine du réseau puis lancer une analyse complète','Supprimer tous les fichiers personnels','Réinstaller le navigateur',2,1),

-- ============================================================
-- DÉBUTANT — Mises à jour (+18)
-- ============================================================
('debutant','Mises à jour','Qu''est-ce qu''une faille "zero-day" ?','Une mise à jour quotidienne automatique','Une vulnérabilité inconnue de l''éditeur, exploitée avant qu''un correctif existe','Un bug mineur sans conséquence','Un antivirus de nouvelle génération',2,1),
('debutant','Mises à jour','Pourquoi les cybercriminels ciblent-ils souvent les systèmes non mis à jour ?','Les vieux systèmes sont plus rapides à pirater','Les failles connues et corrigées dans les mises à jour restent exploitables sur les machines non mises à jour','Les systèmes anciens sont plus rentables','Les mises à jour augmentent les performances',2,1),
('debutant','Mises à jour','Que sont les mises à jour "critiques" ou "de sécurité" ?','Des améliorations de l''interface graphique uniquement','Des correctifs urgents qui bouchent des failles de sécurité importantes','Des mises à jour facultatives','Des mises à jour uniquement pour les entreprises',2,1),
('debutant','Mises à jour','Quelle est la différence entre une mise à jour et une mise à niveau ?','Il n''y en a aucune','Une mise à jour corrige et améliore la version actuelle ; une mise à niveau passe à une version majeure supérieure','Une mise à niveau est gratuite, pas une mise à jour','Une mise à jour concerne le matériel',2,1),
('debutant','Mises à jour','À quelle fréquence Microsoft publie-t-il ses mises à jour de sécurité ?','Tous les jours','Une fois par an','Chaque deuxième mardi du mois ("Patch Tuesday")','Aléatoirement',3,1),
('debutant','Mises à jour','Qu''est-ce qu''un "patch" ?','Un autocollant de protection d''écran','Un correctif logiciel appliqué pour résoudre un problème ou boucher une faille','Un nouveau système d''exploitation','Un type de sauvegarde',2,1),
('debutant','Mises à jour','Pourquoi faut-il aussi mettre à jour ses applications (navigateur, PDF, etc.) ?','Pour avoir une interface plus moderne','Ces applications peuvent aussi contenir des failles exploitables si elles ne sont pas à jour','Les applications ne reçoivent jamais de mises à jour de sécurité','Pour libérer de l''espace disque',2,1),
('debutant','Mises à jour','Que risque-t-on à utiliser un système d''exploitation dont le support est terminé (ex : Windows XP) ?','Rien du tout, les vieux systèmes sont plus stables','Plus aucune mise à jour de sécurité n''est publiée, les failles découvertes ne seront jamais corrigées','Le système s''éteint automatiquement','Le fabricant peut accéder à distance à la machine',2,1),
('debutant','Mises à jour','Qu''est-ce que le "patch management" en entreprise ?','La gestion des contrats avec les fournisseurs','Le processus d''identification, de test et de déploiement des correctifs de sécurité sur les systèmes','La gestion des sauvegardes quotidiennes','Un système d''authentification centralisé',2,1),
('debutant','Mises à jour','Est-il prudent de désactiver les mises à jour automatiques pour "gagner du temps" ?','Oui, les mises à jour sont rarement utiles','Non, les mises à jour automatiques garantissent que les correctifs de sécurité sont appliqués rapidement','Oui, on peut les faire manuellement une fois par an','Oui, les mises à jour automatiques exposent à de nouveaux bugs',2,1),
('debutant','Mises à jour','Qu''est-ce qu''un firmware ?','Un logiciel de sécurité','Le logiciel embarqué dans le matériel (routeur, imprimante...) qui nécessite aussi des mises à jour','Un type de virus','Un protocole réseau',2,1),
('debutant','Mises à jour','Pourquoi faut-il redémarrer l''ordinateur après certaines mises à jour ?','Pour que l''ordinateur refroidisse','Certaines mises à jour nécessitent un redémarrage pour remplacer des fichiers système en cours d''utilisation','Pour vérifier la connexion internet','Le redémarrage est inutile après une mise à jour',2,1),
('debutant','Mises à jour','Que faire si une mise à jour provoque un problème sur votre ordinateur ?','La désinstaller immédiatement sans vérification','Signaler le problème et chercher si un correctif est disponible, certains éditeurs proposent une marche arrière','Formater le disque dur','Ignorer le problème',2,1),
('debutant','Mises à jour','Quel est le danger d''une fausse notification de mise à jour sur un site web ?','Aucun danger','Elle peut inciter l''utilisateur à télécharger un logiciel malveillant déguisé en mise à jour légitime','Elle ralentit uniquement la navigation','Elle efface les cookies du navigateur',2,1),
('debutant','Mises à jour','Les antivirus ont-ils besoin d''être mis à jour ?','Non, un antivirus installé est efficace pour toujours','Oui, leurs bases de données de signatures doivent être mises à jour régulièrement pour détecter les nouvelles menaces','Seulement lors de l''achat d''un nouvel ordinateur','Oui, mais uniquement une fois par an',2,1),
('debutant','Mises à jour','Qu''est-ce que la "gestion des vulnérabilités" ?','Un cours de yoga pour développeurs','Le processus continu d''identification, d''évaluation et de correction des failles de sécurité d''un système','Une technique de sauvegarde','Un type de pare-feu',2,1),
('debutant','Mises à jour','Quel acteur est responsable des mises à jour de sécurité d''un smartphone ?','Uniquement l''opérateur téléphonique','Le fabricant du téléphone et/ou l''éditeur du système d''exploitation','L''utilisateur en écrivant le code lui-même','Les applications installées',2,1),
('debutant','Mises à jour','Combien de temps en moyenne s''écoule entre la découverte d''une faille et son exploitation par des attaquants ?','Plusieurs années','Souvent quelques jours ou semaines, d''où l''importance d''appliquer rapidement les correctifs','Jamais moins d''un an','Exactement 6 mois',2,1),

-- ============================================================
-- DÉBUTANT — Emails suspects (+18)
-- ============================================================
('debutant','Emails suspects','Qu''est-ce que le "spoofing" d''email ?','Un filtre anti-spam','La falsification de l''adresse d''expéditeur pour faire croire que l''email vient d''une source de confiance','Un protocole de chiffrement d''email','Une technique d''archivage des emails',2,1),
('debutant','Emails suspects','Quel est le signe le plus évident qu''un email est frauduleux ?','Il contient des images','L''adresse email de l''expéditeur ne correspond pas au domaine officiel de l''organisation prétendue','Il est écrit en HTML','Il est reçu le week-end',2,1),
('debutant','Emails suspects','Vous recevez un email de votre "banque" vous demandant de cliquer sur un lien pour "vérifier votre compte". Que faire ?','Cliquer sur le lien et vérifier','Ne pas cliquer, aller directement sur le site officiel de la banque en tapant l''URL manuellement','Répondre à l''email pour demander confirmation','Transférer l''email à des amis',2,1),
('debutant','Emails suspects','Qu''est-ce qu''une pièce jointe malveillante ?','Un fichier trop lourd pour l''email','Un fichier attaché contenant un code malveillant qui s''exécute à l''ouverture','Un email sans images','Une photo en haute résolution',2,1),
('debutant','Emails suspects','Quel type de fichier joint est particulièrement dangereux ?','Fichiers .txt','Fichiers .exe, .js, .vbs ou documents Office avec macros activées','Fichiers .png','Fichiers .csv',2,1),
('debutant','Emails suspects','Un email vous promet un gain de 500€ si vous répondez dans l''heure. Que faire ?','Répondre immédiatement','L''ignorer et le signaler comme spam : c''est une arnaque classique','Transférer à la police','Cliquer sur le lien pour réclamer le gain',2,1),
('debutant','Emails suspects','Qu''est-ce que le "vishing" ?','Du phishing par email','Du phishing par appel téléphonique ou message vocal','Du phishing par SMS','Du phishing par courrier postal',2,1),
('debutant','Emails suspects','Qu''est-ce que le "smishing" ?','Du phishing par email','Du phishing par SMS','Du phishing par appel téléphonique','Du phishing par réseau Wi-Fi',2,1),
('debutant','Emails suspects','Comment vérifier si un lien dans un email est sûr sans le cliquer ?','En l''imprimant','En survolant le lien pour voir l''URL réelle dans la barre de statut du navigateur','En copiant le texte du lien','En demandant à son antivirus',2,1),
('debutant','Emails suspects','Un collègue vous envoie un email urgent demandant un virement bancaire immédiat. Que faire ?','Effectuer le virement sans tarder','Appeler directement le collègue par téléphone pour confirmer la demande avant tout virement','Envoyer l''argent et prévenir ensuite','Refuser par email',2,1),
('debutant','Emails suspects','Qu''est-ce que la "fraude au président" (BEC) ?','Une arnaque ciblant les associations','Une attaque où un escroc se fait passer pour un dirigeant pour ordonner des virements frauduleux','Un virus qui cible les PDG','Un type de ransomware',2,1),
('debutant','Emails suspects','Pourquoi les emails de phishing créent-ils souvent un sentiment d''urgence ?','Pour être plus lisibles','Pour pousser la victime à agir vite sans réfléchir ni vérifier','Pour respecter les délais légaux','Pour tester la réactivité des employés',2,1),
('debutant','Emails suspects','Que vérifier en priorité avant d''ouvrir une pièce jointe ?','Le poids du fichier','L''identité réelle de l''expéditeur et la pertinence de la pièce jointe dans le contexte','La date d''envoi de l''email','La police de caractères utilisée',2,1),
('debutant','Emails suspects','Qu''est-ce qu''un filtre anti-spam ?','Un logiciel qui bloque les images dans les emails','Un système qui détecte et isole automatiquement les emails indésirables ou suspects','Un protocole d''envoi d''email sécurisé','Un antivirus spécialisé',2,1),
('debutant','Emails suspects','Vous recevez un email avec l''objet "IMPORTANT : Votre compte va être supprimé". Que ressentez-vous et que faites-vous ?','Panique et clic immédiat sur le lien','Méfiance : cette urgence est un classique du phishing. Vérifier directement sur le site officiel','Répondre pour protester','Supprimer votre compte par précaution',2,1),
('debutant','Emails suspects','Pourquoi certains emails de phishing contiennent-ils des fautes d''orthographe ?','Les pirates ne parlent pas français','Certaines campagnes sont automatiques, mais d''autres le font intentionnellement pour filtrer les victimes vigilantes','Les filtres anti-spam bloquent les emails parfaits','C''est obligatoire légalement dans certains pays',2,1),
('debutant','Emails suspects','Qu''est-ce que le protocole SPF (Sender Policy Framework) ?','Un système de chiffrement des emails','Un mécanisme qui permet aux serveurs de vérifier que l''expéditeur d''un email est autorisé pour ce domaine','Un format d''archivage d''email','Un type de filtre anti-spam manuel',2,1),
('debutant','Emails suspects','Comment reconnaître un lien de phishing dans un email ?','Il commence toujours par "danger-"','L''URL affichée semble correcte mais le lien réel pointe vers un domaine différent ou une variante proche','Il est toujours en rouge','Il contient uniquement des chiffres',2,1),

-- ============================================================
-- DÉBUTANT — HTTPS (+18)
-- ============================================================
('debutant','HTTPS','Que signifie TLS dans le contexte de HTTPS ?','Transport Layer Safety','Transport Layer Security — protocole qui chiffre les communications entre le navigateur et le serveur','Transfer Link Security','Technical Link Standard',2,1),
('debutant','HTTPS','Qu''est-ce qu''un certificat SSL/TLS ?','Une autorisation de créer un site web','Un fichier numérique qui authentifie l''identité d''un site et permet le chiffrement des échanges','Un type de mot de passe','Un protocole de messagerie',2,1),
('debutant','HTTPS','Peut-on être victime de phishing sur un site HTTPS ?','Non, HTTPS garantit qu''un site est sûr','Oui, HTTPS chiffre la connexion mais ne garantit pas que le site est légitime','Non, HTTPS vérifie le contenu du site','Seulement si le site utilise un certificat expiré',2,1),
('debutant','HTTPS','Que se passe-t-il si le certificat d''un site est expiré ?','Le site fonctionne normalement','Le navigateur affiche un avertissement car la connexion sécurisée n''est plus garantie','Le site est automatiquement supprimé d''internet','Cela améliore la vitesse du site',2,1),
('debutant','HTTPS','Qu''est-ce qu''une autorité de certification (CA) ?','Un organisme gouvernemental qui régule internet','Un organisme de confiance qui délivre et valide les certificats numériques','Un fournisseur d''accès internet','Un type d''antivirus en ligne',2,1),
('debutant','HTTPS','HTTP et HTTPS — quelle est la différence principale ?','HTTPS est plus rapide','HTTPS chiffre les données échangées entre le navigateur et le serveur, HTTP les envoie en clair','HTTP utilise le port 443','HTTPS est réservé aux sites gouvernementaux',2,1),
('debutant','HTTPS','Sur quel port fonctionne HTTPS par défaut ?','80','21','443','8080',3,1),
('debutant','HTTPS','Qu''est-ce que le "contenu mixte" (mixed content) sur une page HTTPS ?','Une page avec plusieurs langues','Une page HTTPS chargeant des ressources (images, scripts) en HTTP non chiffré, créant une faille','Une page avec plusieurs polices de caractères','Un site avec HTTP et HTTPS sur des pages différentes',2,1),
('debutant','HTTPS','Pourquoi est-il risqué de saisir ses coordonnées bancaires sur un site HTTP ?','HTTP est plus lent pour traiter les paiements','Les données transitent en clair et peuvent être interceptées par un attaquant','HTTP n''accepte pas les paiements par carte','HTTP facture une commission supplémentaire',2,1),
('debutant','HTTPS','Qu''est-ce qu''une attaque "man-in-the-middle" en lien avec HTTPS ?','Un attaquant qui vole physiquement un serveur','Un attaquant qui s''interpose entre l''utilisateur et le serveur pour intercepter ou modifier les échanges','Une attaque ciblant le milieu du fichier','Un type de déni de service',2,1),
('debutant','HTTPS','HTTPS protège-t-il contre les virus sur le site visité ?','Oui, HTTPS bloque tous les malwares','Non, HTTPS chiffre uniquement la transmission des données, pas le contenu du site','Oui, grâce au certificat','Seulement si le certificat est EV (Extended Validation)',2,1),
('debutant','HTTPS','Qu''est-ce que HSTS (HTTP Strict Transport Security) ?','Un nouveau protocole remplaçant HTTPS','Un mécanisme qui force le navigateur à utiliser uniquement HTTPS pour un site donné','Un type de certificat numérique','Un outil de test de sécurité',2,1),
('debutant','HTTPS','Que signifie le cadenas vert (ou gris) dans la barre d''adresse d''un navigateur ?','Le site est certifié sans danger','La connexion est chiffrée via HTTPS','Le site appartient à un gouvernement','Le site est rapide',2,1),
('debutant','HTTPS','Qu''est-ce qu''un certificat "auto-signé" ?','Un certificat signé par une grande autorité reconnue','Un certificat signé par le propriétaire lui-même, non vérifié par une autorité de confiance','Un certificat délivré automatiquement et totalement fiable','Un certificat valable 10 ans',2,1),
('debutant','HTTPS','Pourquoi les navigateurs modernes marquent-ils les sites HTTP comme "non sécurisé" ?','Pour inciter les utilisateurs à payer','Pour alerter que les données saisies peuvent être interceptées en clair','HTTP est interdit depuis 2020','Pour promouvoir un concurrent',2,1),
('debutant','HTTPS','Quel protocole HTTPS a-t-il remplacé ?','FTP','SSL (Secure Sockets Layer), désormais considéré comme obsolète','HTTP/2','SMTP',2,1),
('debutant','HTTPS','Qu''est-ce que le "certificate pinning" ?','Une technique pour afficher un certificat à l''écran','Une méthode pour associer un hôte à un certificat spécifique afin d''éviter les certificats frauduleux','Un système de renouvellement automatique','Un type de cadenas physique',2,1),
('debutant','HTTPS','Let''s Encrypt est-il une autorité de certification fiable ?','Non, c''est un site frauduleux','Oui, c''est une CA à but non lucratif reconnue qui délivre des certificats HTTPS gratuits','Non, c''est payant et peu connu','Oui, mais uniquement pour les sites gouvernementaux',2,1),

-- ============================================================
-- INTERMÉDIAIRE — Phishing (+17)
-- ============================================================
('intermediaire','Phishing','Qu''est-ce que le "whaling" ?','Du phishing ciblant les baleines en mer','Du spear phishing ciblant spécifiquement les hauts dirigeants d''une organisation (PDG, CFO...)','Un phishing envoyé massivement','Un type de malware',2,1),
('intermediaire','Phishing','Quelles sont les techniques utilisées pour rendre un email de phishing convaincant ?','Uniquement des fautes d''orthographe','Copier l''identité visuelle d''une marque, créer l''urgence, usurper l''adresse d''expéditeur','Utiliser uniquement du texte sans images','Envoyer depuis une adresse inconnue',2,1),
('intermediaire','Phishing','Qu''est-ce que le "pharming" ?','Du phishing par téléphone','Une attaque qui redirige l''utilisateur vers un faux site en manipulant le DNS ou le fichier hosts','Un type d''antivirus','Un protocole de sécurité réseau',2,1),
('intermediaire','Phishing','Comment le SPF, DKIM et DMARC aident-ils contre le phishing ?','Ce sont des antivirus pour les serveurs mail','Ces protocoles permettent de vérifier l''authenticité de l''expéditeur d''un email et réduisent l''usurpation d''identité','Ils chiffrent uniquement le contenu des emails','Ils filtrent les pièces jointes',2,1),
('intermediaire','Phishing','Qu''est-ce qu''un "kit de phishing" ?','Un outil de formation à la sécurité','Un ensemble de modèles et scripts permettant à des attaquants peu techniques de lancer facilement des campagnes de phishing','Une boîte à outils pour administrateurs réseau','Un logiciel antiphishing',2,1),
('intermediaire','Phishing','Pourquoi les campagnes de phishing ciblent-elles souvent les périodes de fêtes ou d''événements majeurs ?','Pour des raisons techniques','Les utilisateurs sont plus occupés, moins vigilants et plus enclins à cliquer','Les serveurs sont moins surveillés','Les emails sont moins filtrés',2,1),
('intermediaire','Phishing','Qu''est-ce que la "typosquatting" ?','Une technique de saisie rapide','L''enregistrement de noms de domaine proches de sites légitimes pour piéger les utilisateurs (ex: g00gle.com)','Un type de logiciel espion','Une technique de cryptographie',2,1),
('intermediaire','Phishing','Comment un test de phishing interne en entreprise est-il utile ?','Il est illégal','Il permet de mesurer le niveau de sensibilisation des employés et d''identifier ceux qui ont besoin de formation','Il remplace l''antivirus','Il détecte les virus sur les postes',2,1),
('intermediaire','Phishing','Qu''est-ce que la "compromission d''email professionnel" (BEC — Business Email Compromise) ?','Un bug de messagerie','Une attaque où un cybercriminel compromet ou usurpe un compte email professionnel pour escroquer l''organisation','Un type de spam','Un virus de messagerie',2,1),
('intermediaire','Phishing','Quelle est la différence entre phishing et pharming ?','Il n''y en a aucune','Le phishing trompe l''utilisateur avec un lien ; le pharming le redirige automatiquement vers un faux site sans clic','Le pharming est plus ancien','Le phishing cible uniquement les emails',2,1),
('intermediaire','Phishing','Qu''est-ce qu''un "clone phishing" ?','Un phishing utilisant des clones vocaux','La duplication d''un email légitime en remplaçant les liens par des liens malveillants','Un phishing ciblant les réseaux sociaux','Un phishing utilisant des photos volées',2,1),
('intermediaire','Phishing','Pourquoi l''IA est-elle de plus en plus utilisée dans les attaques de phishing ?','L''IA est plus rapide pour envoyer des emails','L''IA permet de générer des emails de phishing ultra-personnalisés et sans fautes, plus difficiles à détecter','L''IA remplace les humains dans les entreprises','L''IA bloque les filtres anti-spam',2,1),
('intermediaire','Phishing','Qu''est-ce que la "sensibilisation à la sécurité" (security awareness) ?','Un logiciel de détection','La formation régulière des utilisateurs pour reconnaître et réagir correctement aux menaces comme le phishing','Un type de pare-feu humain','Un protocole réseau',2,1),
('intermediaire','Phishing','Une landing page de phishing affiche un cadenas HTTPS. Cela signifie-t-il que le site est fiable ?','Oui, HTTPS garantit la fiabilité','Non, HTTPS chiffre juste la connexion mais ne valide pas la légitimité du site','Oui, les sites frauduleux ne peuvent pas avoir HTTPS','Oui, si le cadenas est vert',2,1),
('intermediaire','Phishing','Qu''est-ce que le "pretexting" ?','Un email sans objet','La création d''un scénario fictif convaincant (faux contexte) pour manipuler la victime et obtenir des informations','Un type de malware','Un protocole d''authentification',2,1),
('intermediaire','Phishing','Comment signaler un email de phishing en France ?','En le supprimant','En le transférant à signal-spam.fr ou phishing-initiative.fr','En appelant son fournisseur internet','En changeant son mot de passe',2,1),
('intermediaire','Phishing','Quel indicateur permet de détecter qu''un site de phishing imite un site légitime ?','La couleur du fond de page','L''URL du site ne correspond pas exactement au domaine officiel (ex: paypa1.com vs paypal.com)','La présence d''un logo','La vitesse de chargement de la page',2,1),

-- ============================================================
-- INTERMÉDIAIRE — Ransomware (+17)
-- ============================================================
('intermediaire','Ransomware','Quel a été l''impact mondial de l''attaque WannaCry en 2017 ?','Quelques dizaines d''ordinateurs infectés','Des centaines de milliers d''ordinateurs infectés dans 150 pays, dont des hôpitaux et administrations','Uniquement des serveurs en Asie','Des problèmes uniquement sur Windows XP',2,1),
('intermediaire','Ransomware','Pourquoi les hôpitaux sont-ils des cibles privilégiées des ransomwares ?','Ils ont des systèmes très modernes','Leurs données sont critiques, ils sont moins bien protégés et plus enclins à payer rapidement','Ils ont plus d''ordinateurs','Ils utilisent Linux',2,1),
('intermediaire','Ransomware','Faut-il payer la rançon demandée par un ransomware ?','Oui, c''est la solution la plus rapide','En général non : rien ne garantit la récupération des données et cela finance les criminels','Oui, si la somme est inférieure à 100€','Oui, les assurances remboursent toujours',2,1),
('intermediaire','Ransomware','Qu''est-ce que la règle de sauvegarde "3-2-1" ?','3 mots de passe, 2 antivirus, 1 pare-feu','3 copies des données, sur 2 supports différents, dont 1 hors site (ou hors ligne)','3 disques durs, 2 en réseau, 1 chiffré','Sauvegarder 3 fois par jour',2,1),
('intermediaire','Ransomware','Comment un ransomware se propage-t-il généralement dans une entreprise ?','Par le réseau électrique','Via un email malveillant, un site web compromis, ou un accès RDP mal sécurisé','Par les imprimantes réseau','Par les mises à jour Windows',2,1),
('intermediaire','Ransomware','Qu''est-ce qu''un ransomware "double extorsion" ?','Un ransomware qui chiffre deux fois les fichiers','Un ransomware qui chiffre les données ET menace de les publier si la rançon n''est pas payée','Un ransomware nécessitant deux clés de déchiffrement','Un ransomware ciblant deux entreprises simultanément',2,1),
('intermediaire','Ransomware','Quel service peut aider à déchiffrer certains fichiers sans payer la rançon ?','La police nationale uniquement','Le site No More Ransom (nomoreransom.org) qui propose des outils de déchiffrement gratuits','Google Drive uniquement','Les fournisseurs antivirus le font automatiquement',2,1),
('intermediaire','Ransomware','Qu''est-ce que le "Ransomware-as-a-Service" (RaaS) ?','Un abonnement antivirus','Un modèle commercial où des développeurs louent leur ransomware à des affiliés pour partager les rançons','Un service de récupération de données','Un assurance contre les ransomwares',2,1),
('intermediaire','Ransomware','Pourquoi les cryptomonnaies sont-elles souvent utilisées pour payer les rançons ?','Elles sont plus rapides à transférer','Elles offrent un pseudonymat aux attaquants, rendant le traçage plus difficile','Elles sont acceptées par toutes les banques','Elles sont imposées par les attaquants par obligation légale',2,1),
('intermediaire','Ransomware','Quelle mesure immédiate prendre si un ransomware est détecté sur un poste ?','Redémarrer pour espérer annuler le chiffrement','Déconnecter immédiatement le poste du réseau pour limiter la propagation','Payer la rançon rapidement','Supprimer tous les fichiers',2,1),
('intermediaire','Ransomware','Quel rôle joue un EDR (Endpoint Detection and Response) contre les ransomwares ?','Il sauvegarde automatiquement les données','Il détecte les comportements suspects en temps réel et peut bloquer le chiffrement avant qu''il ne se propage','Il remplace l''antivirus traditionnel','Il chiffre les données avant le ransomware',2,1),
('intermediaire','Ransomware','Qu''est-ce qu''un "locker ransomware" ?','Un ransomware qui chiffre les fichiers','Un ransomware qui bloque l''accès à l''interface du système sans chiffrer les fichiers','Un ransomware ciblant les serveurs NAS','Un ransomware exigeant un virement bancaire',2,1),
('intermediaire','Ransomware','Pourquoi les sauvegardes en ligne (cloud) ne protègent-elles pas toujours contre les ransomwares ?','Elles sont toujours sécurisées','Si la sauvegarde est synchronisée en temps réel, les fichiers chiffrés peuvent écraser les versions saines','Le cloud est trop lent','Les ransomwares n''attaquent pas le cloud',2,1),
('intermediaire','Ransomware','Qu''est-ce que la "cyber-assurance" en lien avec les ransomwares ?','Un antivirus professionnel','Une assurance qui couvre les pertes financières liées à une cyberattaque, parfois y compris le paiement de rançons','Un service de déchiffrement gratuit','Un label de sécurité pour les entreprises',2,1),
('intermediaire','Ransomware','Comment le principe de "moindre privilège" réduit-il l''impact d''un ransomware ?','Il n''a aucun impact','En limitant les droits des utilisateurs, le ransomware ne peut chiffrer que les fichiers accessibles au compte infecté','Il bloque automatiquement le ransomware','Il chiffre les fichiers avant le ransomware',2,1),
('intermediaire','Ransomware','Qu''est-ce qu''un "wiper" malware, différent d''un ransomware ?','Un logiciel de nettoyage','Un malware qui détruit définitivement les données sans demander de rançon','Un ransomware ciblant les imprimantes','Un ransomware gratuit',2,1),
('intermediaire','Ransomware','Quelle organisation française est compétente pour signaler une attaque par ransomware ?','Interpol uniquement','L''ANSSI (Agence Nationale de la Sécurité des Systèmes d''Information) et les services de police/gendarmerie','Le ministère des finances','La CNIL uniquement',2,1),

-- ============================================================
-- INTERMÉDIAIRE — Authentification à deux facteurs (+18)
-- ============================================================
('intermediaire','Authentification à deux facteurs','Quels sont les trois facteurs d''authentification possibles ?','Quelque chose que vous savez, avez et êtes (connaissance, possession, inhérence)','Identifiant, mot de passe et email','Nom, prénom et date de naissance','Mot de passe, PIN et code postal',1,1),
('intermediaire','Authentification à deux facteurs','Pourquoi le SMS est-il considéré comme le facteur 2FA le moins sécurisé ?','Les SMS sont trop lents','Il est vulnérable au SIM swapping et à l''interception réseau (SS7)','Les SMS coûtent trop cher','Les téléphones ne reçoivent pas toujours les SMS',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que le "SIM swapping" ?','L''échange physique de carte SIM','Une attaque où un fraudeur convainc l''opérateur de transférer votre numéro vers sa propre SIM','Un bug de réseau mobile','Un type de virus pour téléphone',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce qu''une clé de sécurité matérielle (ex: YubiKey) ?','Un disque dur portable','Un dispositif physique USB/NFC générant un second facteur d''authentification très sécurisé','Un type de carte SIM','Un générateur de mots de passe',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que TOTP (Time-based One-Time Password) ?','Un mot de passe permanent','Un code unique valable seulement 30 secondes, généré par une application comme Google Authenticator','Un SMS d''authentification','Un mot de passe basé sur la date',2,1),
('intermediaire','Authentification à deux facteurs','Que faire si vous perdez votre téléphone utilisé pour la 2FA ?','Créer un nouveau compte','Utiliser les codes de récupération sauvegardés au moment de l''activation de la 2FA','Attendre que le téléphone soit retrouvé','Il est impossible de récupérer l''accès',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que FIDO2/WebAuthn ?','Un protocole de messagerie chiffrée','Un standard d''authentification sans mot de passe utilisant des clés cryptographiques, résistant au phishing','Un type de VPN','Un protocole de sauvegarde',2,1),
('intermediaire','Authentification à deux facteurs','La 2FA protège-t-elle contre le phishing de mot de passe ?','Oui, totalement','Partiellement : certaines attaques de phishing en temps réel (real-time phishing) peuvent contourner certains 2FA par SMS','Non, la 2FA est inutile','Uniquement si combinée à un VPN',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que la "fatigue MFA" (MFA fatigue) ?','Une allergie aux notifications','Une technique d''attaque qui inonde l''utilisateur de demandes d''authentification jusqu''à ce qu''il accepte par erreur','Un problème de batterie de téléphone','Un bug dans les applications d''authentification',2,1),
('intermediaire','Authentification à deux facteurs','Quelle application d''authentification est recommandée par les experts en sécurité ?','WhatsApp','Des applications dédiées comme Authy, Microsoft Authenticator ou Google Authenticator','Les SMS natifs','L''application Calendrier',2,1),
('intermediaire','Authentification à deux facteurs','Pourquoi faut-il sauvegarder ses codes de récupération 2FA ?','Pour les partager avec des collègues','En cas de perte du second facteur, ils permettent de retrouver l''accès au compte','Ils améliorent la sécurité','Ils remplacent le mot de passe principal',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que l''authentification adaptative ?','Une 2FA qui change chaque jour','Un système qui ajuste le niveau d''authentification requis selon le contexte (localisation, comportement...)','Une authentification sans facteur','Un type de reconnaissance faciale',2,1),
('intermediaire','Authentification à deux facteurs','La biométrie (empreinte, Face ID) est-elle un facteur d''authentification ?','Non, c''est uniquement décoratif','Oui, c''est un facteur d''inhérence ("quelque chose que vous êtes")','Non, c''est un mot de passe','Oui, mais uniquement sur iPhone',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que l''authentification "passwordless" ?','Un système sans aucune sécurité','Une authentification sans mot de passe traditionnel, utilisant des clés cryptographiques, la biométrie ou des liens magiques','Un mot de passe très court','Un système réservé aux entreprises',2,1),
('intermediaire','Authentification à deux facteurs','Pourquoi activer la 2FA sur son compte email est-il particulièrement important ?','L''email est souvent lent','L''email est souvent utilisé pour réinitialiser les mots de passe d''autres services : le compromettre donne accès à tout','L''email stocke beaucoup de fichiers','Pour recevoir les SMS plus rapidement',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce que l''authentification unique (SSO — Single Sign-On) ?','Un seul mot de passe pour un seul service','Un système permettant de s''authentifier une seule fois pour accéder à plusieurs applications','Un type de 2FA','Un gestionnaire de mots de passe',2,1),
('intermediaire','Authentification à deux facteurs','Quel est le principal risque du SSO (Single Sign-On) ?','Il est trop lent','Si le compte SSO est compromis, l''attaquant accède à toutes les applications connectées','Il nécessite internet en permanence','Il ne fonctionne que sur mobile',2,1),
('intermediaire','Authentification à deux facteurs','Qu''est-ce qu''un OTP (One-Time Password) ?','Un mot de passe permanent','Un code à usage unique, valable pour une seule session ou transaction','Un mot de passe très court','Un type de clé de chiffrement',2,1),

-- ============================================================
-- INTERMÉDIAIRE — Protection des données (+17)
-- ============================================================
('intermediaire','Protection des données','Que signifie RGPD ?','Règlement Général de Protection Digitale','Règlement Général sur la Protection des Données (règlement européen entré en vigueur en mai 2018)','Réseau de Gestion des Protocoles Défensifs','Règlement Global de Protection Documentaire',2,1),
('intermediaire','Protection des données','Qu''est-ce qu''une donnée à caractère personnel ?','Uniquement le nom et prénom','Toute information permettant d''identifier directement ou indirectement une personne physique','Un fichier professionnel','Une donnée chiffrée',1,1),
('intermediaire','Protection des données','Quels sont les droits des personnes sur leurs données personnelles selon le RGPD ?','Aucun droit particulier','Droit d''accès, de rectification, d''effacement, de portabilité, d''opposition et de limitation du traitement','Uniquement le droit de suppression','Le droit de consulter uniquement',2,1),
('intermediaire','Protection des données','Qu''est-ce que la "minimisation des données" dans le RGPD ?','Compresser les données pour gagner de l''espace','Ne collecter que les données strictement nécessaires à la finalité déclarée du traitement','Chiffrer toutes les données','Supprimer les données après 24h',2,1),
('intermediaire','Protection des données','Qu''est-ce qu''une violation de données personnelles ?','Un bug dans une base de données','Tout incident entraînant la destruction, perte, altération ou divulgation non autorisée de données personnelles','Un accès lent aux données','La sauvegarde de données',2,1),
('intermediaire','Protection des données','Dans quel délai une violation de données doit-elle être notifiée à la CNIL ?','24 heures','72 heures à partir du moment où l''organisation en a connaissance','7 jours','30 jours',2,1),
('intermediaire','Protection des données','Qu''est-ce que la CNIL ?','Un organisme privé de cybersécurité','La Commission Nationale de l''Informatique et des Libertés, autorité française de protection des données','Un tribunal informatique','Un syndicat de développeurs',2,1),
('intermediaire','Protection des données','Qu''est-ce que la "privacy by design" ?','Un logiciel de confidentialité','L''intégration de la protection des données dès la conception d''un système ou produit','Un type de chiffrement','Un label de qualité',2,1),
('intermediaire','Protection des données','Qu''est-ce qu''un DPO (Data Protection Officer) ?','Un antivirus d''entreprise','Le délégué à la protection des données, responsable de la conformité RGPD au sein d''une organisation','Un développeur spécialisé','Un prestataire de sauvegarde',2,1),
('intermediaire','Protection des données','Le droit à l''oubli permet-il de supprimer toutes ses données de partout sur internet ?','Oui, totalement','Non, il permet de demander la suppression des données mais avec des limites légales (intérêt public, archives...)','Oui, en 24h','Uniquement sur Google',2,1),
('intermediaire','Protection des données','Qu''est-ce que la pseudonymisation des données ?','La suppression définitive des données','Le remplacement des informations directement identifiantes par des pseudonymes, les données restant réidentifiables','Un type de chiffrement irréversible','La publication de données anonymes',2,1),
('intermediaire','Protection des données','Quelle sanction maximale prévoit le RGPD ?','Une simple mise en demeure','20 millions d''euros ou 4% du chiffre d''affaires mondial annuel, selon le montant le plus élevé','500€ d''amende','Un avertissement public',2,1),
('intermediaire','Protection des données','Qu''est-ce qu''un cookie et pourquoi faut-il les gérer ?','Un fichier système Windows','Un petit fichier stocké par le navigateur permettant de tracer l''activité de l''utilisateur, nécessitant son consentement selon le RGPD','Un type de malware','Un fichier de configuration serveur',2,1),
('intermediaire','Protection des données','Qu''est-ce que le "consentement" au sens du RGPD ?','Une signature papier obligatoire','Un accord libre, spécifique, éclairé et univoque de la personne pour le traitement de ses données','Un simple clic sur "J''accepte" sans information','Une obligation de partager ses données',2,1),
('intermediaire','Protection des données','Qu''est-ce que la portabilité des données ?','Le transfert de données entre serveurs','Le droit pour une personne de récupérer ses données dans un format lisible et de les transférer à un autre service','La sauvegarde automatique','La vente de données',2,1),
('intermediaire','Protection des données','Les données de santé sont-elles des données sensibles au sens du RGPD ?','Non, elles sont publiques','Oui, elles font partie des catégories particulières de données nécessitant une protection renforcée','Seulement si numérisées','Uniquement si partagées avec un médecin',2,1),
('intermediaire','Protection des données','Qu''est-ce qu''une analyse d''impact sur la protection des données (AIPD/DPIA) ?','Un audit financier','Une évaluation obligatoire pour les traitements à risque élevé, pour identifier et réduire les risques sur les données personnelles','Un rapport annuel obligatoire pour toutes les entreprises','Un test de performance de base de données',2,1),

-- ============================================================
-- INTERMÉDIAIRE — Réseaux (+16)
-- ============================================================
('intermediaire','Réseaux','Qu''est-ce que le modèle OSI ?','Un système d''exploitation','Un modèle en 7 couches décrivant les fonctions d''un réseau de communication','Un protocole de sécurité','Un type de câble réseau',2,1),
('intermediaire','Réseaux','Quelle est la différence entre TCP et UDP ?','Il n''y en a aucune','TCP garantit la livraison et l''ordre des paquets ; UDP est plus rapide mais sans garantie de livraison','TCP est plus rapide','UDP est utilisé uniquement pour les emails',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''une adresse MAC ?','L''adresse d''un appareil Apple','L''identifiant physique unique attribué à la carte réseau d''un équipement','L''adresse IP d''un Mac','Un type de protocole réseau',2,1),
('intermediaire','Réseaux','Qu''est-ce que le DHCP ?','Un protocole de chiffrement','Un protocole qui attribue automatiquement des adresses IP aux appareils d''un réseau','Un type de pare-feu','Un protocole de messagerie',2,1),
('intermediaire','Réseaux','Qu''est-ce que le DNS et quel est son rôle ?','Un antivirus réseau','Un système qui traduit les noms de domaine (ex: google.com) en adresses IP','Un protocole de chiffrement','Un type de câble réseau',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''une attaque par empoisonnement DNS (DNS poisoning) ?','Un virus qui détruit les serveurs DNS','Une attaque qui corrompt le cache DNS pour rediriger les utilisateurs vers de faux sites','Un bug dans les navigateurs','Un type de déni de service',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''un réseau Wi-Fi public non sécurisé ?','Un réseau avec un mot de passe court','Un réseau ouvert où les communications ne sont pas chiffrées, permettant à un attaquant de les intercepter','Un réseau lent','Un réseau gouvernemental',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''une attaque ARP spoofing ?','Un type de phishing','Une attaque qui associe l''adresse MAC de l''attaquant à l''adresse IP d''une victime pour intercepter son trafic','Un bug réseau courant','Un type de ransomware',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''un sous-réseau (subnet) ?','Un réseau de sous-marins','Une subdivision logique d''un réseau IP permettant d''organiser et segmenter le trafic','Un type de câble réseau','Un protocole d''authentification',2,1),
('intermediaire','Réseaux','Qu''est-ce que NAT (Network Address Translation) ?','Un type d''antivirus réseau','Un mécanisme qui permet à plusieurs appareils de partager une seule adresse IP publique','Un protocole de chiffrement','Un type de pare-feu',2,1),
('intermediaire','Réseaux','Sur quel port fonctionne le protocole HTTP par défaut ?','443','25','80','21',3,1),
('intermediaire','Réseaux','Qu''est-ce qu''un proxy ?','Un type de malware','Un serveur intermédiaire entre le client et le serveur de destination, pouvant filtrer ou anonymiser le trafic','Un protocole de sauvegarde','Un type de disque dur réseau',2,1),
('intermediaire','Réseaux','Qu''est-ce que le "sniffing" réseau ?','Un antivirus renifleur','La capture et l''analyse des paquets de données circulant sur un réseau','Un type d''attaque par force brute','Un protocole de compression',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''IPv6 ?','La sixième version du protocole IP, offrant un espace d''adressage immense (128 bits) pour répondre à l''épuisement des adresses IPv4','Un type de pare-feu','Un protocole de messagerie sécurisé','Un antivirus réseau',1,1),
('intermediaire','Réseaux','Qu''est-ce que le "war driving" ?','Une attaque militaire','La pratique consistant à se déplacer pour détecter des réseaux Wi-Fi ouverts ou vulnérables','Un protocole réseau militaire','Un type de malware mobile',2,1),
('intermediaire','Réseaux','Qu''est-ce qu''un VLAN (Virtual Local Area Network) ?','Un réseau Wi-Fi virtuel','Un réseau local virtuel permettant de segmenter logiquement un réseau physique pour améliorer la sécurité','Un protocole de chiffrement','Un type de câble réseau',2,1),

-- ============================================================
-- EXPERT — Chiffrement (+16)
-- ============================================================
('expert','Chiffrement','Quelle est la différence entre chiffrement symétrique et asymétrique ?','Il n''y en a aucune','Symétrique : une seule clé pour chiffrer et déchiffrer ; Asymétrique : une paire clé publique/clé privée','Symétrique est plus sécurisé','Asymétrique utilise des mots de passe',2,1),
('expert','Chiffrement','Quel algorithme de chiffrement symétrique est le standard actuel ?','DES','AES (Advanced Encryption Standard), notamment AES-256','RSA','MD5',2,1),
('expert','Chiffrement','Qu''est-ce que RSA en cryptographie ?','Un antivirus','Un algorithme de chiffrement asymétrique basé sur la difficulté de factoriser de grands nombres premiers','Un protocole réseau','Un algorithme de hachage',2,1),
('expert','Chiffrement','Qu''est-ce qu''une fonction de hachage cryptographique ?','Une fonction de chiffrement réversible','Une fonction qui transforme des données en une empreinte de taille fixe, irréversible et sensible aux modifications','Un algorithme de compression','Un protocole de signature',2,1),
('expert','Chiffrement','Pourquoi MD5 est-il déconseillé pour le stockage de mots de passe ?','Il est trop lent','Il est considéré comme cassé : des collisions ont été trouvées et il est trop rapide pour les attaques par force brute','Il n''est pas disponible sur tous les systèmes','Il génère des empreintes trop longues',2,1),
('expert','Chiffrement','Qu''est-ce que la cryptographie à courbe elliptique (ECC) ?','Un algorithme de hachage','Une cryptographie asymétrique basée sur les courbes elliptiques, offrant une sécurité élevée avec des clés plus courtes','Un protocole de chiffrement symétrique','Un type d''algorithme de compression',2,1),
('expert','Chiffrement','Qu''est-ce qu''un "rainbow table" et comment s''en protéger ?','Un type de pare-feu','Une table précalculée de hachages ; on s''en protège avec le "salage" (ajout d''un sel aléatoire avant le hachage)','Un outil de déchiffrement automatique','Un type de malware',2,1),
('expert','Chiffrement','Qu''est-ce que le "salage" (salting) d''un mot de passe ?','L''ajout de sel marin pour la sécurité','L''ajout d''une chaîne aléatoire (sel) au mot de passe avant hachage pour rendre les rainbow tables inefficaces','Un chiffrement supplémentaire','La compression d''un mot de passe',2,1),
('expert','Chiffrement','Qu''est-ce que PGP (Pretty Good Privacy) ?','Un protocole réseau','Un système de chiffrement hybride (symétrique + asymétrique) pour sécuriser emails et fichiers','Un antivirus email','Un type de VPN',2,1),
('expert','Chiffrement','Qu''est-ce que TLS 1.3 apporte par rapport à TLS 1.2 ?','Il est moins sécurisé','Une handshake plus rapide, la suppression des algorithmes obsolètes et une meilleure confidentialité persistante','Aucune différence notable','Il est compatible uniquement avec HTTPS',2,1),
('expert','Chiffrement','Qu''est-ce que la "confidentialité persistante" (Perfect Forward Secrecy) ?','Un chiffrement permanent','Une propriété garantissant que la compromission d''une clé à long terme ne compromet pas les sessions passées','Un protocole de sauvegarde','Un type de VPN',2,1),
('expert','Chiffrement','Qu''est-ce qu''une attaque par oracle de rembourrage (padding oracle) ?','Une attaque sur les développeurs Oracle','Une attaque exploitant les messages d''erreur de déchiffrement pour décrypter des données chiffrées','Un type de déni de service','Une attaque sur les bases de données',2,1),
('expert','Chiffrement','Qu''est-ce que la cryptographie quantique ?','Un chiffrement plus rapide grâce aux ordinateurs quantiques','L''utilisation des propriétés quantiques (notamment la mécanique quantique) pour sécuriser les communications','Un futur algorithme de hachage','Un type de VPN quantique',2,1),
('expert','Chiffrement','Pourquoi les ordinateurs quantiques menacent-ils RSA et ECC ?','Ils peuvent deviner les mots de passe','L''algorithme de Shor pourrait factoriser de grands nombres ou résoudre les logarithmes discrets exponentiellement plus vite','Ils peuvent casser tous les algorithmes','Ils accélèrent les attaques par dictionnaire',2,1),
('expert','Chiffrement','Qu''est-ce que le chiffrement de bout en bout (E2EE) ?','Un chiffrement uniquement côté serveur','Un chiffrement où seuls les interlocuteurs peuvent déchiffrer les messages, le serveur ne peut pas y accéder','Un chiffrement du disque dur','Un protocole de VPN',2,1),
('expert','Chiffrement','Qu''est-ce que bcrypt et pourquoi est-il utilisé pour les mots de passe ?','Un algorithme de chiffrement symétrique','Un algorithme de hachage intentionnellement lent avec sel intégré, conçu pour résister aux attaques par force brute','Un protocole réseau','Un type de pare-feu',2,1),

-- ============================================================
-- EXPERT — Force brute (+17)
-- ============================================================
('expert','Force brute','Quelle est la différence entre une attaque par force brute et une attaque par dictionnaire ?','Il n''y en a aucune','Force brute : teste toutes les combinaisons possibles ; dictionnaire : teste une liste de mots courants et variantes','Force brute est plus rapide','Dictionnaire utilise des nombres uniquement',2,1),
('expert','Force brute','Qu''est-ce qu''une attaque "credential stuffing" ?','Une force brute classique','L''utilisation de listes d''identifiants/mots de passe volés pour les tester automatiquement sur d''autres services','Une attaque sur les serveurs de stockage','Un type de phishing',2,1),
('expert','Force brute','Quel outil est couramment utilisé pour les attaques par force brute sur les formulaires web ?','Nmap','Hydra ou Burp Suite Intruder','Wireshark','Metasploit uniquement',2,1),
('expert','Force brute','Qu''est-ce que le "password spraying" ?','Tester un seul mot de passe sur un compte','Tester un petit nombre de mots de passe très courants sur un grand nombre de comptes pour éviter les verrouillages','Une attaque par dictionnaire accélérée','Un type de phishing',2,1),
('expert','Force brute','Pourquoi les GPU sont-ils utilisés pour les attaques par force brute ?','Ils sont moins chers que les CPU','Ils peuvent effectuer des milliards de calculs de hachage par seconde grâce à leur architecture massivement parallèle','Ils consomment moins d''énergie','Ils sont plus précis que les CPU',2,1),
('expert','Force brute','Qu''est-ce qu''un CAPTCHA et comment aide-t-il contre la force brute ?','Un type de chiffrement','Un test permettant de distinguer humains et bots, rendant l''automatisation des tentatives plus difficile','Un protocole d''authentification','Un type de pare-feu',2,1),
('expert','Force brute','Qu''est-ce que le "rate limiting" contre les attaques par force brute ?','La limitation de la bande passante','La restriction du nombre de tentatives de connexion autorisées par unité de temps','Un type de captcha','Un protocole de sécurité réseau',2,1),
('expert','Force brute','Combien de temps faudrait-il théoriquement pour forcer un mot de passe de 12 caractères complexes avec un GPU moderne ?','Quelques secondes','Des millions d''années, rendant l''attaque impraticable','Quelques heures','Quelques jours',2,1),
('expert','Force brute','Qu''est-ce qu''Hashcat ?','Un antivirus','Un outil de récupération/crack de mots de passe par force brute et dictionnaire utilisant le GPU','Un protocole de hachage','Un type de malware',2,1),
('expert','Force brute','Quel mécanisme est utilisé pour rendre bcrypt résistant à la force brute GPU ?','Sa longueur de clé','Un facteur de coût (work factor) qui rend chaque calcul intentionnellement lent','Son algorithme symétrique','Sa taille d''empreinte',2,1),
('expert','Force brute','Qu''est-ce qu''une attaque par force brute sur protocole RDP ?','Une attaque sur les fichiers RDP','Des tentatives automatisées de connexion sur le bureau à distance Windows, souvent depuis internet','Un type de phishing','Une attaque sur les imprimantes',2,1),
('expert','Force brute','Comment l''authentification multi-facteurs protège-t-elle contre la force brute ?','Elle ne protège pas','Même si le mot de passe est trouvé, l''attaquant ne peut pas s''authentifier sans le second facteur','Elle ralentit les tentatives','Elle bloque les adresses IP',2,1),
('expert','Force brute','Qu''est-ce qu''une liste "wordlist" comme rockyou.txt ?','Un dictionnaire anglais','Une liste de millions de mots de passe réels issus de fuites de données, utilisée pour les attaques par dictionnaire','Un outil de hachage','Un protocole réseau',2,1),
('expert','Force brute','Qu''est-ce que le "key stretching" ?','L''allongement d''une clé de chiffrement','Une technique qui augmente artificiellement le temps de calcul d''un hachage pour ralentir les attaques par force brute','Un type d''attaque','Un protocole réseau',2,1),
('expert','Force brute','Quel est l''impact du "salage" sur les attaques par force brute distribuées ?','Aucun impact','Il oblige l''attaquant à recalculer les hachages pour chaque sel unique, rendant la mutualisation des efforts impossible','Il double uniquement le temps de calcul','Il chiffre les mots de passe',2,1),
('expert','Force brute','Qu''est-ce qu''une attaque hybride dans le contexte de la force brute ?','Une attaque combinant phishing et malware','Une combinaison de dictionnaire et de force brute qui teste des variations de mots (leet speak, chiffres ajoutés...)','Une attaque simultanée sur plusieurs cibles','Un type de déni de service',2,1),
('expert','Force brute','Pourquoi faut-il implémenter un délai exponentiel ("exponential backoff") après des tentatives de connexion échouées ?','Pour améliorer les performances','Pour ralentir exponentiellement les attaques automatisées sans bloquer définitivement les utilisateurs légitimes','Pour journaliser les tentatives','Pour économiser de l''énergie serveur',2,1),

-- ============================================================
-- EXPERT — Pare-feu (+17)
-- ============================================================
('expert','Pare-feu','Quelle est la différence entre un pare-feu stateful et stateless ?','Il n''y en a aucune','Stateful analyse le contexte des connexions (état) ; stateless filtre uniquement sur les en-têtes des paquets sans contexte','Stateless est plus sécurisé','Stateful est plus rapide',2,1),
('expert','Pare-feu','Qu''est-ce qu''un pare-feu applicatif (WAF — Web Application Firewall) ?','Un pare-feu physique','Un pare-feu qui analyse le trafic HTTP/HTTPS au niveau applicatif pour protéger les applications web','Un antivirus web','Un proxy inverse',2,1),
('expert','Pare-feu','Qu''est-ce qu''une règle de pare-feu "deny all, permit by exception" ?','Autoriser tout sauf l''explicitement interdit','Bloquer tout le trafic par défaut et n''autoriser que ce qui est explicitement permis','Autoriser tout le trafic entrant','Bloquer uniquement les ports connus',2,1),
('expert','Pare-feu','Qu''est-ce que la translation de port (PAT/NAT) dans un pare-feu ?','Un protocole de chiffrement','Un mécanisme redirigeant le trafic entrant d''un port public vers un port/IP interne spécifique','Un type d''attaque','Un protocole de routage',2,1),
('expert','Pare-feu','Qu''est-ce qu''un IDS (Intrusion Detection System) et en quoi diffère-t-il d''un pare-feu ?','Ils sont identiques','Un IDS détecte et alerte sur les intrusions sans les bloquer ; un pare-feu filtre activement le trafic','Un IDS est un pare-feu avancé','Un IDS remplace le pare-feu',2,1),
('expert','Pare-feu','Qu''est-ce qu''un IPS (Intrusion Prevention System) ?','Un IDS sans alertes','Un système qui détecte et bloque automatiquement les intrusions en temps réel','Un pare-feu logiciel','Un antivirus réseau',2,1),
('expert','Pare-feu','Qu''est-ce que l''inspection SSL/TLS par un pare-feu ?','Le chiffrement du trafic par le pare-feu','Le déchiffrement, inspection puis re-chiffrement du trafic HTTPS par le pare-feu pour détecter les menaces cachées','Un protocole d''authentification','Un type de VPN',2,1),
('expert','Pare-feu','Qu''est-ce qu''une "DMZ" (zone démilitarisée) dans une architecture réseau ?','Une zone géographique protégée','Un sous-réseau isolé hébergeant les services exposés à internet, séparant le réseau interne du réseau externe','Un type de pare-feu','Un protocole de routage',2,1),
('expert','Pare-feu','Qu''est-ce que le "egress filtering" ?','Le filtrage du trafic entrant','Le filtrage du trafic sortant pour empêcher l''exfiltration de données ou les communications de malwares','Un type de VPN','Un protocole d''authentification',2,1),
('expert','Pare-feu','Qu''est-ce qu''un NGFW (Next Generation Firewall) ?','Un pare-feu de dernière génération avec uniquement plus de mémoire','Un pare-feu intégrant inspection applicative, IPS, déchiffrement SSL, contrôle d''identité et threat intelligence','Un antivirus réseau','Un type de proxy',2,1),
('expert','Pare-feu','Qu''est-ce qu''une politique "zero trust" en lien avec les pare-feu ?','Faire confiance à tous les utilisateurs internes','Ne faire confiance à aucun utilisateur ou appareil par défaut, même en réseau interne, et vérifier chaque accès','Bloquer uniquement les utilisateurs externes','Désactiver le pare-feu',2,1),
('expert','Pare-feu','Quel protocole de couche 4 les pare-feu stateless analysent-ils principalement ?','HTTP et HTTPS','Les en-têtes IP/TCP/UDP (adresses IP, ports, protocoles) sans analyse du contenu applicatif','SMTP et FTP','SSH et Telnet',2,1),
('expert','Pare-feu','Qu''est-ce qu''un "honeypot" en complément d''un pare-feu ?','Un pot de miel réel','Un système leurre conçu pour attirer et analyser les attaquants tout en les détournant des systèmes réels','Un type de pare-feu','Un protocole de détection',2,1),
('expert','Pare-feu','Qu''est-ce que la "micro-segmentation" dans un environnement cloud ?','La division des serveurs physiques','L''application de politiques de sécurité au niveau des workloads individuels pour limiter les mouvements latéraux','Un type de pare-feu applicatif','Un protocole de chiffrement',2,1),
('expert','Pare-feu','Pourquoi un pare-feu seul ne suffit-il pas à protéger un réseau ?','Il suffit amplement','Il ne peut pas détecter les menaces internes, les attaques chiffrées sophistiquées ou les 0-day ; il faut une défense en profondeur','Il est trop coûteux','Il ralentit trop le réseau',2,1),
('expert','Pare-feu','Qu''est-ce que le protocole "stateful inspection" dans un pare-feu ?','Un protocole réseau','Une technique qui surveille l''état des connexions actives pour valider que les paquets appartiennent à une session légitime','Un type de VPN','Un protocole d''authentification',2,1),
('expert','Pare-feu','Qu''est-ce que l''UEBA (User and Entity Behavior Analytics) en lien avec la sécurité ?','Un type de pare-feu','Un système analysant les comportements des utilisateurs et équipements pour détecter des anomalies suspects','Un antivirus comportemental','Un protocole réseau',2,1),

-- ============================================================
-- EXPERT — SQL Injection (+17)
-- ============================================================
('expert','SQL Injection','Quel caractère est classiquement utilisé pour tester une injection SQL ?','#','Une apostrophe simple ('')','Un espace','Un point-virgule',2,1),
('expert','SQL Injection','Qu''est-ce qu''une injection SQL de type "UNION" ?','Une technique de jointure normale','Une technique qui combine la requête originale avec une requête UNION SELECT pour extraire des données d''autres tables','Une injection dans les procédures stockées','Un type de XSS',2,1),
('expert','SQL Injection','Qu''est-ce qu''une injection SQL aveugle (blind SQLi) ?','Une injection où l''attaquant est aveugle','Une injection où aucun résultat n''est affiché directement, l''attaquant infère les données par réponses vraies/fausses ou temporelles','Une injection sur les bases de données NoSQL','Une injection par force brute',2,1),
('expert','SQL Injection','Qu''est-ce qu''une injection SQL "time-based" ?','Une attaque planifiée dans le temps','Une technique d''injection aveugle utilisant des délais (ex: SLEEP()) pour inférer des informations','Une injection sur les timestamps','Un type d''attaque DDoS',2,1),
('expert','SQL Injection','Pourquoi les requêtes préparées (prepared statements) protègent-elles contre les injections SQL ?','Elles sont plus rapides','Elles séparent le code SQL des données, les paramètres ne pouvant jamais être interprétés comme du code SQL','Elles chiffrent les données','Elles vérifient uniquement les types de données',2,1),
('expert','SQL Injection','Qu''est-ce que le "WAF bypass" dans le contexte des injections SQL ?','Un contournement du pare-feu réseau','Des techniques utilisées par les attaquants pour contourner les règles d''un WAF (encodage, obfuscation, variations syntaxiques)','Un type d''injection','Un outil de test de sécurité',2,1),
('expert','SQL Injection','Qu''est-ce que SQLMap ?','Un éditeur de bases de données','Un outil automatisé open-source de détection et d''exploitation des injections SQL','Un type de pare-feu','Un ORM Python',2,1),
('expert','SQL Injection','Qu''est-ce que l''injection SQL "out-of-band" ?','Une injection sur des bases de données distantes','Une injection qui exfiltre les données via un canal secondaire (DNS, HTTP) plutôt que la réponse de l''application','Une injection sans réseau','Un type de buffer overflow',2,1),
('expert','SQL Injection','Quel principe de sécurité limite les dégâts d''une injection SQL réussie ?','Le chiffrement des données','Le principe de moindre privilège : l''utilisateur SQL de l''application n''a accès qu''aux données nécessaires','L''utilisation de HTTPS','L''emploi d''un pare-feu réseau',2,1),
('expert','SQL Injection','Qu''est-ce qu''une injection SQL dans un ORDER BY ?','Une technique d''optimisation','Une injection dans une clause ORDER BY qui peut permettre d''extraire des données via des variations de tri','Un bug de base de données','Un type de jointure',2,1),
('expert','SQL Injection','Comment les ORM (Object-Relational Mapping) aident-ils contre les injections SQL ?','Ils remplacent SQL','Ils génèrent des requêtes paramétrées automatiquement, réduisant le risque d''injection si utilisés correctement','Ils chiffrent les données','Ils sont immunisés contre toutes les injections',2,1),
('expert','SQL Injection','Qu''est-ce que OWASP et quel est son lien avec les injections SQL ?','Un protocole de sécurité','Une fondation open-source qui liste les 10 risques web les plus critiques, dont les injections SQL en tête historiquement','Un outil de test automatique','Un type de pare-feu applicatif',2,1),
('expert','SQL Injection','Qu''est-ce que l''injection SQL dans les métadonnées ?','Une injection dans les commentaires','Une injection ciblant les tables système (information_schema) pour cartographier la base de données','Un type d''attaque sur les index','Une injection dans les fichiers de config',2,1),
('expert','SQL Injection','Pourquoi la validation côté client seule ne suffit-elle pas contre les injections SQL ?','Elle est suffisante','La validation côté client peut être contournée (désactivation JS, outils comme Burp) ; seule la validation serveur est fiable','Elle est trop lente','Les navigateurs modernes la bloquent',2,1),
('expert','SQL Injection','Qu''est-ce que le "second order injection" (injection de second ordre) ?','Une injection effectuée deux fois','Une injection stockée en base de données et exécutée ultérieurement par une autre requête','Un type d''injection aveugle','Une injection sur un second serveur',2,1),
('expert','SQL Injection','Comment détecter les tentatives d''injection SQL dans les logs ?','Impossible à détecter','Chercher des patterns suspects : apostrophes, mots-clés SQL (UNION, SELECT, DROP), encodages URL de ces caractères','Utiliser uniquement un antivirus','Analyser uniquement les logs d''erreur',2,1),
('expert','SQL Injection','Qu''est-ce que l''injection NoSQL ?','Une injection SQL sur MongoDB','Une attaque similaire à l''injection SQL mais ciblant les bases de données NoSQL via des opérateurs spéciaux ($where, $gt...)','Un type de XSS','Un bug dans les ORM',2,1),

-- ============================================================
-- EXPERT — Sécurité réseau (+16)
-- ============================================================
('expert','Sécurité réseau','Qu''est-ce qu''une attaque DDoS (Distributed Denial of Service) ?','Un accès non autorisé à un serveur','Une attaque qui inonde un service de requêtes depuis de multiples sources pour le rendre indisponible','Un type de ransomware','Un type d''injection',2,1),
('expert','Sécurité réseau','Qu''est-ce que le protocole IPsec ?','Un protocole de messagerie','Un ensemble de protocoles sécurisant les communications IP par authentification et chiffrement au niveau réseau','Un type de pare-feu','Un protocole de routage',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''un "pivot" dans une attaque réseau ?','Un changement de stratégie','L''utilisation d''une machine compromise pour attaquer d''autres systèmes du réseau interne non directement accessibles','Un type de malware','Un protocole réseau',2,1),
('expert','Sécurité réseau','Qu''est-ce que le mouvement latéral (lateral movement) ?','Un déplacement physique','La technique d''un attaquant qui, depuis un premier poste compromis, progresse vers d''autres systèmes du réseau','Un type d''attaque DDoS','Un protocole de routage',2,1),
('expert','Sécurité réseau','Qu''est-ce que SIEM (Security Information and Event Management) ?','Un type d''antivirus','Un système centralisant et corrélant les logs et événements de sécurité pour détecter les incidents','Un protocole réseau','Un type de pare-feu',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''une APT (Advanced Persistent Threat) ?','Un antivirus avancé','Une attaque sophistiquée et durable menée par des acteurs étatiques ou criminels pour infiltrer une cible à long terme','Un type de ransomware','Un protocole réseau',2,1),
('expert','Sécurité réseau','Qu''est-ce que Wireshark ?','Un antivirus réseau','Un outil d''analyse de paquets réseau (packet analyzer) permettant de capturer et inspecter le trafic','Un type de pare-feu','Un protocole de routage',2,1),
('expert','Sécurité réseau','Qu''est-ce que le protocole 802.1X ?','Un protocole Wi-Fi','Un standard d''authentification réseau permettant de contrôler l''accès au réseau filaire ou sans fil','Un type de pare-feu','Un protocole de routage',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''une attaque BGP hijacking ?','Un type de phishing','La détournement de routes BGP pour rediriger le trafic internet via des nœuds contrôlés par l''attaquant','Un bug de routeur','Un type de DDoS',2,1),
('expert','Sécurité réseau','Qu''est-ce que DNSSEC ?','Un antivirus DNS','Une extension sécurisée du DNS ajoutant des signatures cryptographiques pour authentifier les réponses DNS','Un protocole de chiffrement DNS','Un type de pare-feu',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''un "port scan" et quel outil est emblématique pour le réaliser ?','Une technique de chiffrement','L''exploration des ports ouverts d''une machine ; Nmap est l''outil emblématique','Un type d''attaque DDoS','Un protocole réseau',2,1),
('expert','Sécurité réseau','Qu''est-ce que le protocole SSH et pourquoi est-il préféré à Telnet ?','Un protocole de messagerie','SSH chiffre toutes les communications ; Telnet transmet tout en clair incluant les identifiants','Un protocole de fichiers','SSH est plus rapide',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''un "SOC" (Security Operations Center) ?','Un type de pare-feu','Une équipe dédiée à la surveillance, détection et réponse aux incidents de sécurité en continu','Un protocole de sécurité','Un type d''antivirus',2,1),
('expert','Sécurité réseau','Qu''est-ce que la technique OSINT ?','Un type de malware','La collecte de renseignements à partir de sources ouvertes et publiques pour préparer une attaque ou une défense','Un protocole réseau','Un type de chiffrement',2,1),
('expert','Sécurité réseau','Qu''est-ce que le principe de "défense en profondeur" ?','Avoir un seul pare-feu très puissant','L''empilement de plusieurs couches de sécurité indépendantes pour qu''une défaillance d''une couche ne compromette pas tout','Protéger uniquement le périmètre réseau','Chiffrer toutes les données',2,1),
('expert','Sécurité réseau','Qu''est-ce qu''un test de pénétration (pentest) ?','Une attaque réelle non autorisée','Un test autorisé simulant une attaque réelle pour identifier les vulnérabilités d''un système avant un vrai attaquant','Un scan automatique','Un audit de code',2,1),

-- ============================================================
-- EXPERT — VPN (+17)
-- ============================================================
('expert','VPN','Quels protocoles VPN sont les plus recommandés en 2024 ?','PPTP et L2TP','WireGuard, OpenVPN et IKEv2/IPsec pour leur sécurité et performance','PPTP uniquement','L2TP sans IPsec',2,1),
('expert','VPN','Pourquoi PPTP est-il déconseillé ?','Il est trop lent','Il utilise des algorithmes de chiffrement faibles et des protocoles d''authentification compromis (MS-CHAPv2)','Il est trop coûteux','Il ne fonctionne pas sur mobile',2,1),
('expert','VPN','Qu''est-ce que le "split tunneling" dans un VPN ?','Un tunnel VPN divisé en deux','Une fonctionnalité permettant de choisir quel trafic passe par le VPN et lequel reste en direct','Un type d''attaque VPN','Un protocole de chiffrement',2,1),
('expert','VPN','Qu''est-ce qu''un VPN "no-log" ?','Un VPN sans interface graphique','Un service VPN qui affirme ne conserver aucun journal d''activité ou de connexion de ses utilisateurs','Un VPN sans chiffrement','Un VPN gouvernemental',2,1),
('expert','VPN','Qu''est-ce que la "fuite DNS" (DNS leak) dans un VPN ?','Un bug de serveur DNS','Quand les requêtes DNS passent en dehors du tunnel VPN, révélant les sites visités à l''opérateur ou des tiers','Un type d''attaque','Un bug de routage',2,1),
('expert','VPN','Qu''est-ce que WireGuard et pourquoi est-il populaire ?','Un antivirus réseau','Un protocole VPN moderne avec une base de code réduite (~4000 lignes), très performant et facile à auditer','Un type de pare-feu','Un protocole de messagerie',2,1),
('expert','VPN','Qu''est-ce qu''un VPN d''entreprise (Corporate VPN) ?','Un VPN gratuit pour les employés','Un accès sécurisé et authentifié au réseau interne d''une entreprise depuis l''extérieur','Un type de proxy','Un antivirus professionnel',2,1),
('expert','VPN','Qu''est-ce que le "kill switch" dans un VPN ?','Un bouton d''extinction d''urgence','Une fonctionnalité qui coupe la connexion internet si le VPN se déconnecte, évitant toute fuite de données','Un protocole d''authentification','Un type de pare-feu',2,1),
('expert','VPN','Qu''est-ce qu''un VPN SSL/TLS ?','Un VPN uniquement pour les sites HTTPS','Un VPN utilisant les protocoles SSL/TLS pour sécuriser le tunnel, fonctionnant généralement sur le port 443','Un antivirus HTTPS','Un type de proxy',2,1),
('expert','VPN','Un VPN protège-t-il contre les malwares ?','Oui, totalement','Non, un VPN chiffre uniquement le transit des données mais ne protège pas contre les malwares','Oui, si combiné à un antivirus','Seulement contre les virus réseau',2,1),
('expert','VPN','Qu''est-ce que le "double VPN" (multi-hop) ?','Deux abonnements VPN','Une configuration faisant passer le trafic par deux serveurs VPN successifs pour un anonymat renforcé','Un VPN deux fois plus rapide','Un protocole de chiffrement double',2,1),
('expert','VPN','Qu''est-ce que Tor et en quoi diffère-t-il d''un VPN ?','Tor est un VPN gratuit','Tor passe le trafic par 3 nœuds aléatoires chiffrés pour l''anonymat ; un VPN utilise un seul serveur de confiance','Tor est plus rapide','Tor chiffre uniquement le contenu',2,1),
('expert','VPN','Qu''est-ce que l''obfuscation dans un VPN ?','Un type de chiffrement','Une technique masquant le trafic VPN pour le faire ressembler à du trafic ordinaire, contournant les blocages','Un protocole d''authentification','Un type de pare-feu',2,1),
('expert','VPN','Quelles informations un VPN peut-il théoriquement logger malgré une politique "no-log" ?','Rien du tout','Les timestamps de connexion, les adresses IP source et les volumes de données, selon l''implémentation réelle','Le contenu des sites visités','Les mots de passe utilisés',2,1),
('expert','VPN','Qu''est-ce que le protocole IKEv2 (Internet Key Exchange version 2) ?','Un type de chiffrement','Un protocole de négociation de clé utilisé dans les VPN IPsec, reconnu pour sa vitesse et sa stabilité','Un type de pare-feu','Un protocole de messagerie',2,1),
('expert','VPN','Pourquoi utiliser un VPN sur un réseau Wi-Fi public ?','Pour aller plus vite','Pour chiffrer le trafic et empêcher les attaques d''interception (man-in-the-middle) sur un réseau non sécurisé','Pour accéder à plus de sites','Pour économiser des données mobiles',2,1),
('expert','VPN','Qu''est-ce que la "transparence" d''un fournisseur VPN (transparency report) ?','La visibilité de l''interface','La publication régulière de rapports indiquant les demandes gouvernementales reçues et les données éventuellement communiquées','Un audit de code source','Un label de qualité',2,1);
